_target_: la.pl_modules.resnet.ResNet
name: shake_resnet
input_dim: ???

model:
  _target_: la.modules.shake_resnet.ShakeResNet
  depth: 20
  w_base: 16
  num_classes: ???

optimizer:
  _target_: torch.optim.SGD
  lr: 0.1
  momentum: 0.9
  weight_decay: 1e-4

lr_scheduler:
  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
  T_max: 200

transform_func:
  _target_: torchvision.transforms.Compose
  transforms:
    - _target_: torchvision.transforms.ToTensor
    - _target_: torchvision.transforms.Normalize
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
