seed_index: 0
deterministic: False

results_folder: ${oc.env:PROJECT_ROOT}/results/part_shared_part_novel
results_path:
  cka: ${results_folder}/cka_analysis.json
  classification: ${results_folder}/class_analysis.json
  clustering: ${results_folder}/clustering_analysis.json
  plots: ${results_folder}/plots
  separability: ${results_folder}/separability_analysis.json


# <TODO>: wire this
model:
  _target_: la.pl_modules.student_from_scratch_cnn.StudentFromScratchCNN
  name: student_from_scratch_cnn
  input_dim: ???

  model:
      _target_: la.modules.relative_vanilla_cnn.RelativeCNN
      num_classes: ???
      input_dim: ???
      num_interm_channels: 64 #16
      num_out_channels: 128 #32
      embedding_dim: 128 # 256

  optimizer:
    _target_: torch.optim.Adam

  transform_func:
    _target_: torchvision.transforms.Compose
    transforms:
      - _target_: torchvision.transforms.ToTensor
      - _target_: torchvision.transforms.Normalize
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
# </TODO>

run_analysis:
  cka: False
  classification: False
  clustering: False
  qualitative: False
  separability: False
  distillation: True


has_coarse_label:
  cifar100: True
  tiny_imagenet: False

num_shared_classes:
  cifar100: [80, 60, 40, 20]
  tiny_imagenet: [100, 50]

num_novel_classes:
  cifar100: [10, 5]
  tiny_imagenet: [25]

dataset_names:
  - cifar100
  - tiny_imagenet

model_names:
  # - efficient_net_efficient_net_vanilla_cnn_efficient_net_vanilla_cnn
  # - efficient_net_efficient_net_vanilla_cnn_efficient_net_vanilla_cnn_efficient_net_vanilla_cnn
  # - efficient_net_efficient_net_vanilla_cnn_efficient_net_vanilla_cnn_efficient_net_vanilla_cnn_efficient_net_vanilla_cnn
  # - vanilla_cnn_vanilla_cnn_efficient_net_vanilla_cnn_efficient_net
  - efficient_net
  - vanilla_cnn

num_total_classes:
  cifar100: 100
  tiny_imagenet: 200

classifier_embed_dim: 256

# configurations:
  # - dataset_name: cifar100
  #   model_name: ['efficient_net', 'efficient_net', 'vanilla_cnn', 'efficient_net', 'vanilla_cnn']
  #   num_shared_classes: 80
  #   num_novel_classes: 5

  # - dataset_name: cifar100
  #   model_name: ['efficient_net', 'efficient_net', 'vanilla_cnn', 'efficient_net', 'vanilla_cnn']
  #   num_shared_classes: 60
  #   num_novel_classes: 10

  # - dataset_name: cifar100
  #   model_name: ['efficient_net', 'efficient_net', 'vanilla_cnn', 'efficient_net', 'vanilla_cnn', 'efficient_net', 'vanilla_cnn']
  #   num_shared_classes: 40
  #   num_novel_classes: 10

  # - dataset_name: cifar100
  #   model_name: ['efficient_net', 'efficient_net', 'vanilla_cnn', 'efficient_net', 'vanilla_cnn', 'efficient_net', 'vanilla_cnn', 'efficient_net', 'vanilla_cnn']
  #   num_shared_classes: 20
  #   num_novel_classes: 10

configurations:
# CIFAR100
  # EFFICIENTNET
    # N10
  # - dataset_name: cifar100
  #   model_name: efficient_net
  #   num_shared_classes: 80
  #   num_novel_classes: 10

  # - dataset_name: cifar100
  #   model_name: efficient_net
  #   num_shared_classes: 60
  #   num_novel_classes: 10

  # - dataset_name: cifar100
  #   model_name: efficient_net
  #   num_shared_classes: 40
  #   num_novel_classes: 10

  # - dataset_name: cifar100
  #   model_name: efficient_net
  #   num_shared_classes: 20
  #   num_novel_classes: 10
    # N5
  # - dataset_name: cifar100
  #   model_name: efficient_net
  #   num_shared_classes: 80
  #   num_novel_classes: 5

  # - dataset_name: cifar100
  #   model_name: efficient_net
  #   num_shared_classes: 60
  #   num_novel_classes: 5

  # - dataset_name: cifar100
  #   model_name: efficient_net
  #   num_shared_classes: 40
  #   num_novel_classes: 5

  # - dataset_name: cifar100
  #   model_name: efficient_net
  #   num_shared_classes: 20
  #   num_novel_classes: 5

# # VANILLA CNN
#   # N10
  # - dataset_name: cifar100
  #   model_name: vanilla_cnn
  #   num_shared_classes: 80
  #   num_novel_classes: 10

  # - dataset_name: cifar100
  #   model_name: vanilla_cnn
  #   num_shared_classes: 60
  #   num_novel_classes: 10

  # - dataset_name: cifar100
  #   model_name: vanilla_cnn
  #   num_shared_classes: 40
  #   num_novel_classes: 10

  # - dataset_name: cifar100
  #   model_name: vanilla_cnn
  #   num_shared_classes: 20
  #   num_novel_classes: 10

  # N5
  # - dataset_name: cifar100
  #   model_name: vanilla_cnn
  #   num_shared_classes: 80
  #   num_novel_classes: 5

  # - dataset_name: cifar100
  #   model_name: vanilla_cnn
  #   num_shared_classes: 60
  #   num_novel_classes: 5

  # - dataset_name: cifar100
  #   model_name: vanilla_cnn
  #   num_shared_classes: 40
  #   num_novel_classes: 5

  - dataset_name: cifar100
    model_name: vanilla_cnn
    num_shared_classes: 20
    num_novel_classes: 5

# TINY IMAGENET
# #   EFFICIENTNET
#   - dataset_name: tiny_imagenet
#     model_name: efficient_net
#     num_shared_classes: 100
#     num_novel_classes: 25

#   - dataset_name: tiny_imagenet
#     model_name: efficient_net
#     num_shared_classes: 50
#     num_novel_classes: 25

#   # VANILLACNN
#   - dataset_name: tiny_imagenet
#     model_name: vanilla_cnn
#     num_shared_classes: 100
#     num_novel_classes: 25

#   - dataset_name: tiny_imagenet
#     model_name: vanilla_cnn
#     num_shared_classes: 50
#     num_novel_classes: 25
