defaults:
  - model: vanilla_cnn  # vanilla_cnn, efficient_net

dataset_name: cifar100 # cifar100 or tiny_imagenet
num_shared_classes: 80
num_novel_classes_per_task: 5
data_path: ${oc.env:PROJECT_ROOT}/data/${nn.dataset_name}/part_shared_part_novel/S${nn.num_shared_classes}_N${nn.num_novel_classes_per_task}
output_path: ${nn.data_path}_${nn.model.name}

data:
  _target_: la.data.part_shared_part_novel_datamodule.PartSharedPartNovelDatamodule
  data_path: ${nn.data_path}
  only_use_sample_num: -1 # -1 means use all samples

  gpus: ${train.trainer.gpus}

  num_workers:
    train: 8
    val: 8
    test: 8

  batch_size:
    train: 100
    val: 100
    test: 100
