defaults:
  - model: shake_resnet  # vanilla_cnn, efficient_net, resnet

dataset_name: cifar100 # cifar100 or tiny_imagenet
data_path: ${oc.env:PROJECT_ROOT}/data/${nn.dataset_name}/partitioned
output_path: ${nn.data_path}_${nn.model.name}

data:
  _target_: la.data.aggr_exp_datamodule.MyDataModule
  data_path: ${nn.data_path}
  only_use_sample_num: -1 # -1 means use all samples

  datasets:
    train:
      _target_: la.data.aggr_exp_dataset.MyDataset
      samples: ???
      split: ???

    val:
      _target_: la.data.aggr_exp_dataset.MyDataset
      samples: ???
      split: ???

  gpus: ${train.trainer.gpus}

  num_workers:
    train: 8
    val: 8
    test: 8

  batch_size:
    train: 100
    val: 100
    test: 100
