defaults:
  - model: vanilla_cnn  # vanilla_cnn, efficient_net, resnet, shake_resnet

dataset_name: cifar100 # cifar100 or tiny_imagenet
data_path: ${oc.env:PROJECT_ROOT}/data/${nn.dataset_name}/totally_disjoint/partition-1
output_path: ${nn.data_path}_${nn.model.name}

data:
  _target_: la.data.totally_disjoint_datamodule.TotallyDisjointDatamodule
  data_path: ${nn.data_path}
  only_use_sample_num: 1000 # -1 means use all samples

  gpus: ${train.trainer.gpus}

  num_workers:
    train: 8
    val: 8
    test: 8

  batch_size:
    train: 100
    val: 100
    test: 100
